services:
  mysql:
    image: mysql:8.0.34
    container_name: GAMBLING99MySql
    hostname: GAMBLING99MySql
    env_file: ./.env/MySql.env
    ports:
      - 3306:3306
    networks:
      - gambling99
    volumes:
      - mysql_data:/var/lib/mysql



networks:
  gambling99:
    name: gambling99
volumes:
  mysql_data:
