services:
  user-service:
    image: gambling99-userservice:latest
    container_name: GAMBLING99UserServiceAPI
    build:
      context: ./UserService
      dockerfile: Dockerfile
    hostname: GAMBLING99UserServiceAPI
    env_file: ./.env/UserService.env
    ports:
      - 8080:8080
    networks:
      - gambling99

  auth-service:
    image: gambling99-authservice:latest
    container_name: GAMBLING99AuthServiceAPI
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    hostname: GAMBLING99UserServiceAPI
    env_file: ./.env/AuthService.env
    ports:
      - 8081:8080
    networks:
      - gambling99

  mysql:
    image: mysql:8.0.34
    container_name: GAMBLING99MySql
    hostname: GAMBLING99MySql
    env_file: ./.env/MySql.env
    ports:
      - 3306:3306
    networks:
      - gambling99
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - gambling99

  lobby_service:
    container_name: lobby_service
    build:
      context: ./LobbyService
    ports:
      - 8082:8080
    networks:
      - gambling99

networks:
  gambling99:
    name: gambling99

volumes:
  mysql_data:
