services:
  user-service:
    image: userservice:latest
    container_name: UserServiceAPI
    hostname: UserServiceAPI
    build:
      context: ./UserService
      dockerfile: Dockerfile
    env_file: ./.env/UserService.env
    depends_on:
      - mysql
    ports:
      - 8081:8080
    networks:
      - gambling99

  auth-service:
    image: authservice:latest
    container_name: AuthServiceAPI
    hostname: AuthServiceAPI
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    env_file: ./.env/AuthService.env
    depends_on:
      - mysql
    ports:
      - 8082:8080
    networks:
     - gambling99

  game-service:
    image: gameservice:latest
    container_name: GameServiceAPI
    hostname: GameServiceAPI
    build:
      context: ./GameService
      dockerfile: Dockerfile
    env_file: ./.env/GameService.env
    depends_on:
      - lobby-service
    ports:
      - 8083:8080
    networks:
      - gambling99


  lobby-service:
    image: lobbyservice:latest
    container_name: LobbyServiceAPI
    hostname: LobbyServiceAPI
    build:
      context: ./LobbyService
    ports:
      - 8084:8080
    networks:
      - gambling99


  mysql:
    image: mysql:8.0.34
    container_name: MySql
    hostname: MySql
    env_file: ./.env/MySql.env
    ports:
      - 3306:3306
    networks:
      - gambling99
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
    networks:
      - gambling99

networks:
  gambling99:
    name: gambling99

volumes:
  mysql_data:
