openapi: 3.0.3
info:
  title: Gambling 99
  version: 0.0.9
  description: Microservice API that runs a web based gambling royal game

servers:
  - url: http://LocalHost:8080/
    description: nginx port allows access to all endpoints by adding /[endpoint] to the end
  - url: MySql://MySql:3306
    description: The server for the mysql database
  - url: redis://redis:6379
    description: the server for the redis database

components:
  schemas:
    User:
      type: object
      properties:
        UserId:
          type: integer
        Usernames:
          type: string
        Password:
          type: string
        Email:
          type: string
        Role:
          type: string
    UserForm:
      type: object
      properties:
        Username:
          type: string
        Email:
          type: string 
        Password:
          type: string 
        

tags:
  - name: User
    description: Operations related to user management
  - name: Auth
    description: Login, logout, and token operations
  - name: Game
    description: Game management and operations
  - name: Lobby
    description: Lobby management


paths:
  # ------- User Service ------- #
  /user:
    get:
      tags: [User]
      summary: Get all users
      security:
        - JWT: []
      responses:
        '200':
          description: List of users
          content:
            application/json:
              schema:
                type: array
                item:
                  $ref: '#/components/schemas/User'
        '404':
          description: Users not found
        '500':
          description: Server error

    post:
      tags: [User]
      summary: Create a new user
      requestBody:
        description: intakes a password, username, and email to make a user
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserForm"

    
      responses:
        '201':
          description: User created
          content:
            application/json:
        '403':
          description: Forbidden operation
        '406':
          description: Missing required fields
        '500':
          description: Server error
          
  /user/home:
    get:
      tags: [User]
      summary: Gets house
      responses:
        '200':
          description: House
          content:
            'image/png': 
              schema:
                type: object
                format: binary
        '404':
          description: House not found
        '500':
          description: Server error

  # ------- Auth Service ------- #
  /auth:
    post:
      tags: [Auth]
      summary: Takes in username, email and password, returns JWT token
      requestBody:
        description: intakes a password, username, and email to make a user
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserForm"
      responses:
        '201':
          description: JWT created
          content:
            application/json:
              schema:
                type: object
                properties:
                  JWT:
                    type: string
        '403':
          description: Forbidden operation
        '406':
          description: Missing required fields
        '500':
          description: Server error

  /auth/home:          
    get:
      tags: [Auth]
      summary: Gets house
      responses:
        '200':
          description: House
          content:
            'image/png': 
              schema:
                type: object
                format: binary
        '404':
          description: House not found
        '500':
          description: Server error
  
  # ------- Game service ------- #
  /game/home:
    get:
      tags: [Game]
      summary: Gets house
      responses:
        '200':
          description: House
          content:
            'image/png': 
              schema:
                type: object
                format: binary
        '404':
          description: House not found
        '500':
          description: Server error
  /game:
    get:
      tags: [Game]
      sumary: plays a round of the game
      responses:
        '200':
          description: Succesfully spun slot machine
          content:
            application/json:
              schema:
                type: object
                format: binary
        '401':
          description:
            Bad JWT token
          content:
            applicatoin/json:
              schema:
                type: array
                format: binary

  # ------ Lobby Service ------ #
  /lobby/home:
    get:
      tags: [Lobby]
      summary: gets house
      responses:
        '200':
          description: House
          content:
            'image/png':
              schema:
                type: object
                format: binary
        '404':
          description: House not found
        '500':
          descritpion: Server error
  /lobby:
    get:
      tags: [Lobby]
      summary: gets all lobbies
      responses:
        '200':
          description: returns all lobbies
          content:
            application/json:
              schema:
                type: array
                format: binary
  /lobby/:lobby_id/leaderboard:
    get:
      tags: [Lobby]
      summary: gets lobby leaderboard by id
      responses:
        '200':
          description:
            returns lobby leaderboard by id
          content:
            application/json:
              schema:
                type: object
                format: binary
  /lobby/join:
    post:
      tags: [Lobby]
      summary: posts user to a lobby
      responses:
        '200':
          description: posts a user to a lobby
          content:
            application/json:
              schema:
                type: object
                format: binary
        '400':
          description:  missing required fields or user is already in lobby
          content:
            application/json:
              schema:
                type: object
                format: binary
  /lobby/leave:
    post:
      tags: [Lobby]
      summary: removes user from lobby
      responses:
        '200':
          description: removes a user from the lobby
          content:
            application/json:
              schema:
                type: object
                format: binary
        '400':
          description:  missing user id or user is not in lobby
          content:
            application/json:
              schema:
                type: object
                format: binary
        
  /lobby/create:
    post:
      tags: [Lobby]
      summary: creates a new lobby
      responses: 
        '200':
          description: creates a new lobby
          content:
            application/json:
              schema:
                type: object
                format: binary
        '400':
          description:  missing name or host
          content:
            application/json:
              schema:
                type: object
                format: binary
  /lobby/:id:
    delete:
      tags: [Lobby]
      summary: Deletes a lobby by given id
      responses:
        '200':
          description: deletes the given lobby
          content:
            application/json:
              schema:
                type: object
                format: binary
    patch:
      tags: [Lobby]
      summary: updates the user within a given lobby
      responses:
        '200':
          description:
            updates the user within a given lobby
          content:
            application/json:
              schema:
                type: object
                format: binary
        '400':
          description:  missing name or host
          content:
            application/json:
              schema:
                type: object
                format: binary
        '404':
          description: user not found
          content:
            application/json:
              schema:
                type: object
                format: binary
  /lobby/:user_id/money:
    get:
      tags: [Lobby]
      summary: gets the given users money
      responses:
        '200':
          description:
            gets the given users money
          content:
            application/json:
              schema:
                type: object
                format: binary
        '404':
          description: user not found
          content:
            application/json:
              schema:
                type: object
                format: binary
          

    

